version: '0.1'
services:
  prometheus:
    image: prometheus:latest
    ports:
        - 9000:9000
    volumes:
      - ${PWD}/prometheus/prometheus.yml
  wordpress:
    image: wordpress:latest
    ports:
        - 3000:3001
  grafana:
    image: grafana/grafana
    ports:
        - 80:3000
