version: '3.0'
services:
  prometheus:
    image: prometheus
    ports:
        - 9090:9090
    volumes:
      - ${PWD}/prometheus/prometheus.yml
  wordpress:
    image: wordpress
    ports:
        - 80:80
  grafana:
    image: grafana
    ports:
        - 3000:3000
